create database studentdetails;
use studentdetails;
create table student(rollno int,name varchar(20),address varchar(20),maths int,physics int,computerscience int,total int);
insert into student values(1,'abu','kozhikode',100,80,90,270);
insert into student values(2,'anu','uk',100,80,90,270);
insert into student values(3,'aju','canada',100,100,100,300);
insert into student values(4,'manu','kochi',100,80,90,270);
insert into student values(5,'vani','banglore',100,80,90,270);
insert into student values(6,'abi','goa',100,80,90,270);
insert into student values(7,'lalu','kozhikode',100,80,90,270);
insert into student values(8,'abdu','bali',100,80,90,270);
insert into student values(9,'akash','pala',100,90,90,280);
insert into student values(10,'shibla','palakkad',100,80,100,280);
insert into student values(11,'varun','palakkad',100,80,100,280);
insert into student values(12,'adwaith','palakkad',100,80,100,280);
insert into student values(13,'reema','palakkad',100,80,100,280);
insert into student values(14,'sarag','palakkad',100,80,100,280);
select * from student;
select rollno,name from student;
select rollno,name from student where total>250;
select name from student where address='canada';
delete from student where name='sarag';
update student set name='robin z' where name='adwaith';
select * from student where address='kozhikode' OR 'korea';
alter table student add column department varchar(10);
select * from student;
select name,department from student order by name desc ;
update student set address = NULL where rollno = 2 ;
select * from student where address = NULL ;
select max(total) from student;
select min(physics) from student ;
select avg(computerscience) from student ; 
select sum(physics) from student; 
update student set department = 'MCA' where rollno = 1;
update student set department = 'MCA'  where rollno = 2;
update student set department = 'CSEng'  where rollno = 3;
update student set department = 'MCA'  where rollno = 4;
update student set department = 'CvilEng'  where rollno = 5;
update student set department = 'MCA'  where rollno = 6;
update student set department = 'MCA'  where rollno = 7;
update student set department = 'MCA'  where rollno = 8;
update student set department = 'EEEng'  where rollno = 9;
update student set department = 'MCA'  where rollno = 10;
update student set department = 'MCA'  where rollno = 11;
update student set department = 'MCA'  where rollno = 12;
update student set department = 'MECHEng'  where rollno = 13;
update student set department = 'EEEng'  where rollno = 14;
select * from student ;
select department from student where department like '%g' ; 
select name from student where name like 'a%' ; 
alter table student drop total ;
alter table student add column total varchar(5);
update student set total=maths+physics+computerscience where rollno=1;
update student set total=maths+physics+computerscience where rollno=2;
update student set total=maths+physics+computerscience where rollno=3;
update student set total=maths+physics+computerscience where rollno=4;
update student set total=maths+physics+computerscience where rollno=5;
update student set total=maths+physics+computerscience where rollno=6;
update student set total=maths+physics+computerscience where rollno=7;
update student set total=maths+physics+computerscience where rollno=8;
update student set total=maths+physics+computerscience where rollno=9;
update student set total=maths+physics+computerscience where rollno=10;
update student set total=maths+physics+computerscience where rollno=11;
update student set total=maths+physics+computerscience where rollno=12;
update student set total=maths+physics+computerscience where rollno=13;
update student set total=maths+physics+computerscience where rollno=14;
select * from student;
create view studentdetails as select rollno,name,total from student;
alter table student add age int;
update student set age=36 where rollno=1;
update student set age=32 where rollno=2;
update student set age=34 where rollno=3;
update student set age=26 where rollno=4;
update student set age=16 where rollno=5;
update student set age=33 where rollno=6;
update student set age=31 where rollno=7;
update student set age=22 where rollno=8;
update student set age=36 where rollno=9;
update student set age=24 where rollno=10;
update student set age=23 where rollno=11;
update student set age=33 where rollno=12;
update student set age=15 where rollno=13;
update student set age=19 where rollno=14;
select * from student;
delete from student where age=26;
select * from student;
rollback;
select * from student;
commit;





