create database studentdetailss;
use studentdetailss;
create table studentn(rollno int,name varchar(20),address varchar(20),maths int,physics int,computerscience int,total int);
insert into studentn values(1,'abu','kozhikode',100,80,90,270);
insert into studentn values(2,'anu','uk',100,80,90,270);
insert into studentn values(3,'aju','canada',100,100,100,300);
insert into studentn values(4,'manu','kochi',100,80,90,270);
insert into studentn values(5,'vani','banglore',100,80,90,270);
insert into studentn values(6,'abi','goa',100,80,90,270);
insert into studentn values(7,'lalu','kozhikode',100,80,90,270);
insert into studentn values(8,'abdu','bali',100,80,90,270);
insert into studentn values(9,'akash','pala',100,90,90,280);
insert into studentn values(10,'shibla','palakkad',100,80,100,280);
insert into studentn values(11,'varun','palakkad',100,80,100,280);
insert into studentn values(12,'adwaith','palakkad',100,80,100,280);
insert into studentn values(13,'reema','palakkad',100,80,100,280);
insert into studentn values(14,'sarag','palakkad',100,80,100,280);
select * from studentn;
select rollno,name from studentn;
select rollno,name from studentn where total>250;
select name from studentn where address='canada';
delete from studentn where name='sarag';
update studentn set name='robin z' where name='adwaith';
select * from studentn where address='kozhikode' OR 'korea';
alter table studentn add column department varchar(10);
select * from studentn;
select name,department from studentn order by name desc ;
select * from studentn where address = NULL ;
select max(total) from studentn;
select min(physics) from studentn ;
select avg(computerscience) from studentn ; 
select sum(physics) from studentn; 
update studentn set department = 'MCA' where rollno = 1;
update studentn set department = 'MCA'  where rollno = 2;
update studentn set department = 'CSEng'  where rollno = 3;
update studentn set department = 'MCA'  where rollno = 4;
update studentn set department = 'CvilEng'  where rollno = 5;
update studentn set department = 'MCA'  where rollno = 6;
update studentn set department = 'MCA'  where rollno = 7;
update studentn set department = 'MCA'  where rollno = 8;
update studentn set department = 'EEEng'  where rollno = 9;
update studentn set department = 'MCA'  where rollno = 10;
update studentn set department = 'MCA'  where rollno = 11;
update studentn set department = 'MCA'  where rollno = 12;
update studentn set department = 'MECHEng'  where rollno = 13;
update studentn set address = 'uk'  where rollno = 2;

select * from studentn ;
select department from studentn where department like '%g' ; 
select name from studentn where name like 'a%' ; 
alter table studentn drop total ;
alter table studentn add column total varchar(5);
select * from studentn ;

